Be explicit about 'data' usage
While compiling with GCC 6.0.0 (r234771) in C++1z mode compiler
produces extra diagnotic messages:

    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:47:3: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:103:30: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:104:27: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:110:31: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:111:5: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:116:5: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:121:5: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:137:26: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:138:7: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:230:4: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:239:6: error: reference to 'data' is ambiguous
    L1Trigger/GlobalCaloTrigger/test/testElectronSorter.cpp:250:16: error: reference to 'data' is ambiguous
    RecoVertex/BeamSpotProducer/test/global.h:35:25: error: template argument 1 is invalid
    RecoVertex/BeamSpotProducer/test/global.h:35:25: error: template argument 2 is invalid
    RecoVertex/BeamSpotProducer/test/global.h:36:31: error: expected initializer before 'zDataConstIter'
    RecoVertex/BeamSpotProducer/test/global.h:37:25: error: expected initializer before 'zDataIter'

Avoid using plain 'data', because in C++1z (C++17) there is a new
std::data() function and if using namespace std exist it could
result in unexpected result visible in above diagnotic messages.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>